src/app/app.module.ts, src/app/components/busqueda-cuenta-corriente-cliente/busqueda-cuenta-corriente-cliente.component.html, src/app/components/cuenta-corriente-cliente-modal/cuenta-corriente-cliente-modal.component.html, src/app/components/pedido/pedido.component.html, src/app/components/pedido/pedido.component.ts, src/app/components/producto-modal/producto-modal.component.html, src/app/components/producto-modal/producto-modal.component.ts, src/app/components/renglon-pedido-modal/renglon-pedido-modal.component.html, src/app/components/ver-pedido/ver-pedido.component.html, src/app/components/ver-pedido/ver-pedido.component.scss, src/app/models/cliente.ts, src/app/models/producto.ts
=> Bonificación por Producto y límite por monto en Pedido.

src/app/components/facturas-compra/facturas-compra.component.html, src/app/components/facturas-compra/facturas-compra.component.ts, src/app/components/ver-factura/ver-factura.component.html, src/app/models/criterias/busqueda-factura-compra-criteria.ts, src/app/models/factura-compra.ts
=>  Fecha de alta en factura de compra

src/app/components/cantidad-producto-modal/cantidad-producto-modal.component.html, src/app/components/cantidad-producto-modal/cantidad-producto-modal.component.ts, src/app/components/factura-venta/factura-venta.component.html, src/app/components/pedido/pedido.component.html, src/app/components/pedido/pedido.component.ts, src/app/components/producto-modal/producto-modal.component.html, src/app/components/producto-modal/producto-modal.component.ts, src/app/components/producto/producto.component.ts, src/app/components/productos/productos.component.html, src/app/components/ver-producto/ver-producto.component.html, src/app/models/configuracion-scursal.ts, src/app/models/producto-faltante.ts, src/app/models/producto.ts, src/app/models/renglon-pedido.ts, src/app/models/sucursal.ts, src/app/services/productos.service.ts, src/styles.scss
=> Propiedad de "Comparte stock" en Sucursal

src/app/components/productos/productos.component.ts
=> Agregar a los criterios de búsqueda de productos, el de proveedor y el de rubro

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/components/notas-credito-compra-home/notas-credito-compra-home.component.html, src/app/components/notas-credito-compra-home/notas-credito-compra-home.component.ts, src/app/components/notas-credito-compra/notas-credito-compra.component.html, src/app/components/notas-credito-compra/notas-credito-compra.component.scss, src/app/components/notas-credito-compra/notas-credito-compra.component.ts, src/app/components/notas-credito-venta/notas-credito-venta.component.ts, src/app/components/notas-debito-compra-home/notas-debito-compra-home.component.html, src/app/components/notas-debito-compra-home/notas-debito-compra-home.component.ts, src/app/components/notas-debito-compra/notas-debito-compra.component.html, src/app/components/notas-debito-compra/notas-debito-compra.component.scss, src/app/components/notas-debito-compra/notas-debito-compra.component.ts, src/app/components/notas/notas-credito.component.ts, src/app/components/notas/notas-debito.component.ts, src/app/components/notas/notas.component.ts, src/app/components/side-nav/side-nav.component.html, src/app/components/ver-nota/ver-nota.component.html, src/app/components/ver-nota/ver-nota.component.ts, src/app/models/nota.ts
=>  Agregar las secciones de credito y debito para compras

src/app/app.component.scss, src/app/components/home/home.component.html, src/app/components/home/home.component.scss, src/app/components/home/home.component.ts, src/app/components/nav-bar/nav-bar.component.html, src/app/components/side-nav/side-nav.component.html, src/app/components/side-nav/side-nav.component.scss, src/styles.scss
=> Mover el menú al lado de la derecha

src/app/components/productos/productos.component.ts, src/app/models/criterias/busqueda-producto-criteria.ts
=> Permitir agregar criterios de ordenamiento adicionales a la búsqueda de producto.

src/app/app-routing.module.ts, src/app/components/side-nav/side-nav.component.html, src/app/feature-modules/formas-de-pago/components/formas-de-pago/formas-de-pago.component.html, src/app/feature-modules/formas-de-pago/components/formas-de-pago/formas-de-pago.component.ts, src/app/feature-modules/formas-de-pago/formas-de-pago-routing.module.ts, src/app/feature-modules/formas-de-pago/formas-de-pago.module.ts, src/app/modules/share.module.ts, src/app/services/formas-de-pago.service.ts
=> Agregar la sección de formas de pago en administración

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/components/configuracion/configuracion.component.html, src/app/components/configuracion/configuracion.component.ts, src/app/components/side-nav/side-nav.component.html, src/app/components/side-nav/side-nav.component.ts, src/app/models/configuracion-sucursal.ts, src/app/models/sucursal.ts, src/app/modules/share.module.ts, src/app/services/configuraciones-sucursal.service.ts
=> Agregar el menú de sistema, únicamente para el Rol Administrador, e incluir la sección de configuración.

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/components/side-nav/side-nav.component.html, src/app/components/usuario-form/usuario-form.component.html, src/app/components/usuario-form/usuario-form.component.ts, src/app/directives/recibos.directive.ts, src/app/feature-modules/usuarios/components/usuario/usuario.component.html, src/app/feature-modules/usuarios/components/usuario/usuario.component.ts, src/app/feature-modules/usuarios/components/usuarios/usuarios.component.html, src/app/feature-modules/usuarios/components/usuarios/usuarios.component.ts, src/app/feature-modules/usuarios/usuarios-routing.module.ts, src/app/feature-modules/usuarios/usuarios.module.ts, src/app/modules/share.module.ts, src/app/services/usuarios.service.ts
=> Agregar a la menú de configuración, la sección de usuarios.

src/app/app-routing.module.ts, src/app/components/side-nav/side-nav.component.html, src/app/feature-modules/sucursales/components/sucursal/sucursal.component.html, src/app/feature-modules/sucursales/components/sucursal/sucursal.component.scss, src/app/feature-modules/sucursales/components/sucursal/sucursal.component.ts, src/app/feature-modules/sucursales/components/sucursales/sucursales.component.html, src/app/feature-modules/sucursales/components/sucursales/sucursales.component.ts, src/app/feature-modules/sucursales/sucursales-routing.module.ts, src/app/feature-modules/sucursales/sucursales.module.ts, src/app/models/nueva-sucursal.ts, src/app/models/sucursal.ts, src/app/modules/share.module.ts, src/app/services/helper.service.ts, src/app/services/sucursales.service.ts
=> Agregar al menú de configuración, la sección de sucursales (Alta y Modificación)

src/app/app-routing.module.ts, src/app/components/productos/productos.component.ts, src/app/components/side-nav/side-nav.component.html, src/app/feature-modules/localidades/components/localidad/localidad.component.html, src/app/feature-modules/localidades/components/localidad/localidad.component.ts, src/app/feature-modules/localidades/components/localidades/localidades.component.html, src/app/feature-modules/localidades/components/localidades/localidades.component.ts, src/app/feature-modules/localidades/localidades-routing.module.ts, src/app/feature-modules/localidades/localidades.module.ts, src/app/models/criterias/busqueda-localidad-criteria.ts, src/app/models/localidad.ts, src/app/modules/share.module.ts, src/app/services/ubicaciones.service.ts
=> Agregar al menú de administración, la sección de Localidades

src/app/app-routing.module.ts, src/app/components/producto-multi-editor/producto-multi-editor.component.ts, src/app/components/producto/producto.component.ts, src/app/components/side-nav/side-nav.component.html, src/app/feature-modules/medidas/components/medida/medida.component.html, src/app/feature-modules/medidas/components/medida/medida.component.ts, src/app/feature-modules/medidas/components/medidas/medidas.component.html, src/app/feature-modules/medidas/components/medidas/medidas.component.ts, src/app/feature-modules/medidas/medidas-routing.module.ts, src/app/feature-modules/medidas/medidas.module.ts, src/app/feature-modules/rubros/components/rubro/rubro.component.ts, src/app/models/medida.ts, src/app/modules/share.module.ts, src/app/services/medidas.service.ts
=> Agregar al menú de administración, la sección de Medidas

src/app/components/home/home.component.scss, src/app/components/nav-bar/nav-bar.component.html, src/app/components/notas-debito-compra/notas-debito-compra.component.html, src/app/components/notas-debito-venta/notas-debito-venta.component.html, src/app/components/side-nav/side-nav.component.html, src/app/components/side-nav/side-nav.component.scss, src/app/components/side-nav/side-nav.component.ts
=> Sidenav plegable/desplegable

.gitignore, src/app/components/factura-venta/factura-venta.component.html, src/app/components/factura-venta/factura-venta.component.ts, src/app/components/pedido/pedido.component.html, src/app/components/pedido/pedido.component.ts
=> Forma de pago predeterminada en alta Pedido

src/app/components/ver-recibo/ver-recibo.component.html
=>  Agrega el botón de reporte para recibos

src/app/components/facturas-venta/facturas-venta.component.ts, src/app/components/producto-multi-editor/producto-multi-editor.component.html, src/app/components/productos/productos.component.ts
- Clears selection on click in filter and clear filter buttons in productos y facturas-venta components.
- Removes submit event from the form in producto-multi-editor component, only fires submit on click in "Aceptar" button.
=> Merge master changes 

src/app/components/pedido/pedido.component.html, src/app/components/pedido/pedido.component.ts, src/app/modules/share.module.ts
=> Select "Retiro en Sucursal" by default if available

src/app/components/productos/productos.component.ts, src/app/components/ubicacion-form-field/ubicacion-form-field.component.ts, src/app/components/ubicacion-modal-component/ubicacion-modal.component.html, src/app/components/ubicacion-modal-component/ubicacion-modal.component.ts
=> Field "numero" must not allow letters, only number

src/app/components/remitos/remitos.component.html, src/app/feature-modules/gastos/components/ver-gasto/ver-gasto.component.html, src/app/feature-modules/gastos/components/ver-gasto/ver-gasto.component.ts
=> Hotfix20230615

package.json, src/app/components/producto/producto.component.html, src/app/components/producto/producto.component.ts
=> Quality of life changes
